### ISSUE TITLE
Printer Codes for Preheating

### ISSUE THREAD

**Issue by zbhujwala** [ZBoylan/3DPrinterUI#11]
These codes must be sent as with an ArrayList of one element (String) to the Device Controller:

Homing: G48
Heating Bed: M140 S<integer for temperature>
Heating Bed + Waiting: M190 S<integer for temperature>
Heating Head: M104 S<integer for temperature>
Heating Head + Waiting: M109 S<integer for temperature>

To turn off, run the same heating commands with S0.

**Comment by peralta013** [comment]
So, do they have to be sent along with the value of the temperature such as `method("M140 S", 100)`? Also, which Device Controller methods take the printer codes as arguments?

**Comment by zbhujwala** [comment]
It seems like there was a mistake on my part, did not explain the "Heating" properly.

An example of the Heating would be something like M140 S40 to set it to 40 degrees (append the temperature to the S).

As for sending the codes, Device Controller said that they will want an ArrayList<String> with one element, which will be the code for the specific operation.

**Comment by peralta013** [comment]
Please review my most recent pull request. I implemented everything according to the user's input of `headTemp` and `bedTemp`. I did not add anything to the Homing code. Do we need to append something for it?

**Comment by ZBoylan** [comment]
This should be all set. We'll test tomorrow or Wednesday
